FROM node:alpine

RUN apk add --no-cache \
    bash curl git && \
    git clone https://github.com/docker-hy/frontend-example-docker exer

WORKDIR /exer

RUN npm install && \
    apk del curl git && \
    adduser -D app && \
    chown -R app /exer/

USER app

EXPOSE 5000

CMD ["npm", "start"]
