version: "3.5"

services:
    redis:
        image: redis
        container_name: redis
    back:
        image: back
        container_name: back
        environment: 
            - REDIS=redis
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
            - DB_NAME=postgres
            - DB_HOST=db
        build: ./back/
    front:
        image: front
        container_name: front
        build: ./front/
    db: 
        image: postgres
        environment:
            - POSTGRES_PASSWORD=example
        container_name: pgdb
    proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        container_name: proxy
        depends_on: 
            - back
            - front
        ports:
            - 80:80