version: "3"

services:
    redis:
        image: redis
        container_name: redis
    back:
        image: back
        ports: 
            - 8000:8000
        container_name: back
        environment: 
            - REDIS=redis
    front:
        image: front
        ports: 
            - 5000:5000
        container_name: front
