version: "3.5"

services: 
    updater:
        build: .
        image: updater
        container_name: updater
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        stdin_open: true
        tty: true