version: "3.5"

services:
    front:
        image: front
        container_name: front
        build:
            context: ./front/
            dockerfile: Dockerfile.alpine
        ports:
            - 80:80