version: "3"

services: 
    back:
        image: back
        ports: 
            - 8000:8000
        container_name: back
    front:
        image: front
        ports: 
            - 5000:5000
        container_name: front