FROM node:alpine as build-stage

RUN apk add --no-cache \
    bash curl git && \
    git clone https://github.com/docker-hy/frontend-example-docker exer

WORKDIR /exer

RUN npm install && \
    apk del curl git && \
    adduser -D app && \
    chown -R app /exer/ && \
    npm run build

USER app

FROM nginx

COPY --from=build-stage /exer/dist/ /usr/share/nginx/html
