FROM openjdk:8 as build-stage
RUN git clone https://github.com/docker-hy/spring-example-project spring
WORKDIR /spring
RUN ./mvnw package

FROM openjdk:8

COPY --from=build-stage /spring/target /target
RUN useradd -m app && \
    chown -R app /target

USER app

EXPOSE 8080
CMD ["java", "-jar", "/target/docker-example-1.1.3.jar"]